# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Machine Logic
tagline: At the junction of computation, logic and mathematics
email: lp15@cam.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
        Machine Logic is Lawrence Paulson's blog on Isabelle/HOL and related topics.

baseurl:      ""
paginate:     1
locale:       "en"
url: "https://lawrencecpaulson.github.io/"


# About/contact
github_username:  lawrencecpaulson
author:
  name: Lawrence C Paulson
  url:  https://www.cl.cam.ac.uk/~lp15/

# Build settings
theme: jekyll-theme-cayman
markdown: kramdown
plugins:
  - jekyll-feed
show_excerpts: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
